import type { Metadata } from "next";
import { Nav } from "./components/Nav";
import "./globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" bg-slate-400 flex flex-col"
      >
        <Nav/>
        <div className="p-4">
        {children}
        </div>
 
      </body>
    </html>
  );
}
